# Generated by Django 6.1 on 2026-08-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200)),
                ('album_description', models.TextField(blank=True)),
                ('album_photo', models.ImageField(blank=True, null=True, upload_to='album_photos/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
