# Generated by Django 6.1 on 2026-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, help_text='Certificate file (PDF or image) for this degree/program', null=True, upload_to='certificates/'),
        ),
    ]
