# Generated by Django 6.1 on 2026-09-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0003_education_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. GitHub, LinkedIn, Instagram, Email', max_length=50)),
                ('url', models.CharField(help_text='Full URL (or email address for mailto links)', max_length=300)),
                ('icon', models.CharField(blank=True, help_text="Optional Font Awesome class, e.g. 'fa-brands fa-instagram'. Auto-detected from name if blank.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
